# Generated by Django 4.0.5 on 2022-09-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='categories',
            new_name='category',
        ),
    ]
