# Generated by Django 4.0.5 on 2022-09-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_rename_categories_case_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='deadline',
        ),
    ]
