# Generated by Django 4.0.5 on 2022-09-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_alter_case_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Success'), (3, 'Closed'), (4, 'In process of review')], default=4),
        ),
    ]
