# Generated by Django 4.0.5 on 2022-09-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_deadline_alter_case_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='goal',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='case',
            name='raised',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Success'), (3, 'Closed'), (4, 'In Review')], default=4),
        ),
    ]
