# Generated by Django 4.0.5 on 2022-09-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_goal_case_raised_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='status_en',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Success'), (3, 'Closed'), (4, 'In Review')], default=4, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='status_ru',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Success'), (3, 'Closed'), (4, 'In Review')], default=4, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
