# Generated by Django 4.0.5 on 2022-09-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_goal_case_raised_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='location',
            field=models.CharField(default='Bishkek, Kyrgyzstan', max_length=100),
        ),
    ]
