# Generated by Django 4.0.5 on 2022-09-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_case_description_en_case_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='case',
            name='status_ru',
        ),
    ]
